print('Арифметические операторы:')
print("Сложение вещественных чисел:                             2.5 + 2.5 = {result}"   .format(result = 2.5 + 2.5))
print("Вычитание вещественных чисел:                            2.5 - 2.5 = {result}"   .format(result = 2.5 - 2.5))
print("Умножение вещественных чисел:                            2.5 * 2.5 = {result}"   .format(result = 2.5 * 2.5))
print("Деление вещественных чисел:                              2.5 / 2.5 = {result}"   .format(result = 2.5 / 2.5))
print("Модуль четного числа:                                    2.5 % 2.5 = {result}"   .format(result = 2.5 % 2.5))
print("Модуль нечетного числа:                                  3.5 % 2.5 = {result}"   .format(result = 3.5 % 2.5))
print("Деление с остатком вещественных чисел:                   2.5 // 2.5 = {result}"  .format(result = 2.5 // 2.5))
print("Возвращает пару частное-остаток от деления аргументов:   2.5 / 2.5 = {result}"   .format(result = divmod(2.5, 2.5)))
print("Возведение в степень:                                    2.5 ^ 2.5 = {result}"   .format(result = pow(2.5, 2.5)))
print("Получение корня числа:                                   4.5 ** 2.5 = {result}"  .format(result = 2.5 ** (1 / 2.5)))
print("* — операторы присваивания работают аналогичным образом.")

print('\nОператоры сравнения:')
print("Сравнение целых чисел: 5.5 == 2.5: {result}"     .format(result = 5.5 == 2.5))
print("Сравнение целых чисел: 5.5 != 2.5: {result}"     .format(result = 5.5 != 2.5))
print("Сравнение целых чисел: 5.5 < 2.5:  {result}"     .format(result = 5.5 < 2.5))
print("Сравнение целых чисел: 5.5 > 2.5:  {result}"     .format(result = 5.5 > 2.5))
print("Сравнение целых чисел: 5.5 <= 2.5: {result}"     .format(result = 5.5 <= 2.5))
print("Сравнение целых чисел: 5.5 >= 2.5: {result}"     .format(result = 5.5 >= 2.5))

print('\nЛогические операторы:')
print("Логическое И:    5.5 == 2.5 И 5.5 != 2.5:        {result}"     .format(result = 5.5 == 2.5 and 5.5 != 2.5))
print("Логическое !:    ! (5.5 == 2.5 И 5.5 != 2.5):    {result}"     .format(result = not (5.5 == 2.5 and 5.5 != 2.5)))
print("Логическое ИЛИ:  5.5 == 2.5 ИЛИ 5.5 != 2.5:      {result}"     .format(result = 5.5 == 2.5 or 5.5 != 2.5))

print('\nОператоры членства:')
print("Определяет, (IN) входит ли число 2.5 в список: 1, 2, 3, 4: {result}"       .format(result = 2.5 in [1, 2, 3, 4]))
print("Определяет, (NOT IN) входит ли число 2.5 в список: 1, 2, 3, 4: {result}"   .format(result = 2.5 not in [1, 2, 3, 4]))

print('\nОператоры идентификации (Сравнивает id объектов):')
print("Сравнивает id объектов (IS): 2.5 is 2.5: {result}"       .format(result = 2.5 is 2.5))
print("Сравнивает id объектов (IS NOT): 2.5 is 2.5: {result}"   .format(result = 2.5 is not 2.5))

print('\nДругие операции:')
print("Округление числа: 0.75 = {result}".format(result = round(0.75)))
print("Определяет целое число или вещественное: 2.5 = {result}".format(result = (2.5).is_integer()))